### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by Demonith** [velinath/trinity-armory#1]
Severity: Warning

Message: mysqli::real_connect(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Filename: mysqli/mysqli_driver.php

Line Number: 161

Backtrace:

File: C:\xampp\htdocs\armory\application\models\Characters_model.php
Line: 12
Function: database

File: C:\xampp\htdocs\armory\application\controllers\Armory.php
Line: 10
Function: model

File: C:\xampp\htdocs\armory\index.php
Line: 292
Function: require_once
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 323

**Comment by velinath** [comment]
did you install mysql on your server and set up the database? did you configure `config/database.php` correctly?

**Comment by Demonith** [comment]
Why did u stop bro i use latest updated website wow like that was abended 7 years and now 2 guys started again and its amazing what they do plz dont give up !

i setup everything i have made armory to add sql file but have a error 

Do u have discord we can chat there or shell i post here

**Comment by velinath** [comment]
I do not use Discord, apologies.

**Comment by Demonith** [comment]
![untitled](https://cloud.githubusercontent.com/assets/758842/24519730/50a4f6b2-1586-11e7-85b3-7908d712f774.png)

**Comment by Demonith** [comment]
Well i find one that working armory tnx for replaying thou and dont give up on something good luck

**Comment by velinath** [comment]
you'd have to change `your-webserver-ip` to the IP of your webserver. That could be `localhost` if your webserver and database server are on the same machine, or if they're isolated it'd be the internal network address of the webserver.

**Comment by Demonith** [comment]
SQL is problem I think

**Comment by velinath** [comment]
Sounds good. If it's not a problem with the application I'll close ticket then. Good luck.
